"""
xvgParser module is part of DuIvyTools for parsing the xvg file generated by GROMACS.

Written by DuIvy and provided to you by GPLv3 license.
"""

import os
import sys
import math
import numpy as np

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from DIT import log
